default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: mypassword
  host: localhost

development:
  <<: *default
  database: tour_of_heroes_development

test:
  <<: *default
  database: tour_of_heroes_test